### PR TITLE
Redirect /faq to new faqs

### PR DESCRIPTION
**Pull request by just-a-random-person**

### CODE REVIEW

**Comment by just-a-random-person** [comment]
Wait I did something wrong

**Comment by just-a-random-person** [comment]
@Billy-Bloom whats the publish directory for the site? Cuz that’s where the _redirects file would go if you wanted one.

**Comment by Billy-Bloom** [comment]
> @Billy-Bloom whats the publish directory for the site? Cuz that’s where the _redirects file would go if you wanted one.

The build directory

**Comment by edcous** [comment]
> > @Billy-Bloom whats the publish directory for the site? Cuz that’s where the _redirects file would go if you wanted one.
> 
> 
> 
> The build directory

No I mean what's the name of the folder

**Comment by just-a-random-person** [comment]
Let’s see if this works

**Pull request merged**
